{"name": "Проверка оформления заказа авторизованным пользователем", "status": "broken", "statusDetails": {"message": "TypeError: not all arguments converted during string formatting", "trace": "self = <pages.constructor_page.ConstructorPage object at 0x0000017A66EE3FE0>\nlocator = ['xpath', '//p[text() = \"идентификатор заказа\"]/preceding-sibling::h2'], old_text = '9999'\n\n    def wait_until_text_changes(self, locator, old_text):\n        try:\n>           WebDriverWait(self.driver, 5).until_not(\n                expected_conditions.text_to_be_present_in_element(locator, old_text))\n\npages\\base_page.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"510bf5ee-97ea-4e98-939e-01b949e60899\")>\nmethod = <function text_to_be_present_in_element.<locals>._predicate at 0x0000017A66F20680>, message = ''\n\n    def until_not(self, method: Callable[[D], T], message: str = \"\") -> Union[T, Literal[True]]:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value evaluates to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`, or\n                  ``True`` if `method` has raised one of the ignored exceptions\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if not value:\n                    return value\n            except self._ignored_exceptions:\n                return True\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:128: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_constructor_page.TestConstructorPage object at 0x0000017A66DCA1E0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"510bf5ee-97ea-4e98-939e-01b949e60899\")>\nlogin_new_user = {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2IxNzI3OWVkMjgwMDAxYjQwMmYwOSIsImlhdCI6MTcxN...bp8HIVDikqOat-e_Y', 'refreshToken': 'b3a0b9a635946bc2fe373dd0278157163acd52743008f18afe7fec4225f06ba29435c4d55149cb82'}\n\n    @allure.title('Проверка оформления заказа авторизованным пользователем')\n    def test_order_creation_by_authorized_user(self, driver, login_new_user):\n        constructor_page = ConstructorPage(driver)\n        constructor_page.go_to_constructor_page()\n        bun_id = helpers.random_bun_id()\n        ingredient_id = helpers.random_ingredient_id()\n        constructor_page.drag_ingredient_to_order_picking_area(bun_id)\n        constructor_page.drag_ingredient_to_order_picking_area(ingredient_id)\n        constructor_page.click_order_button()\n    \n>       assert constructor_page.check_open_success_screen_with_order_number()\n\ntests\\test_constructor_page.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\constructor_page.py:64: in check_open_success_screen_with_order_number\n    if self.wait_until_text_changes(ConstructorPageLocators.ORDER_NUMBER_ON_SUCCESS_SCREEN, '9999'):\npages\\base_page.py:42: in wait_until_text_changes\n    self.logger.error('Проблема:', e)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1568: in error\n    self._log(ERROR, msg, args, **kwargs)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1684: in _log\n    self.handle(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1700: in handle\n    self.callHandlers(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1762: in callHandlers\n    hdlr.handle(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1028: in handle\n    self.emit(record)\nvenv\\Lib\\site-packages\\_pytest\\logging.py:387: in emit\n    super().emit(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1168: in emit\n    self.handleError(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:1160: in emit\n    msg = self.format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:999: in format\n    return fmt.format(record)\nvenv\\Lib\\site-packages\\_pytest\\logging.py:140: in format\n    return super().format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:703: in format\n    record.message = record.getMessage()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <LogRecord: pages.base_page, 40, C:\\Users\\pev_stasis\\PycharmProjects\\Diplom\\Diplom3_ui_python\\pages\\base_page.py, 42, \"Проблема:\">\n\n    def getMessage(self):\n        \"\"\"\n        Return the message for this LogRecord.\n    \n        Return the message for this LogRecord after merging any user-supplied\n        arguments with the message.\n        \"\"\"\n        msg = str(self.msg)\n        if self.args:\n>           msg = msg % self.args\nE           TypeError: not all arguments converted during string formatting\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py:392: TypeError"}, "steps": [{"name": "Открываем Главную страницу с конструктором", "status": "passed", "start": 1715148587207, "stop": 1715148587371}, {"name": "Определение случайного id булки для заказа", "status": "passed", "start": 1715148587371, "stop": 1715148587371}, {"name": "Определение случайного id ингридиента через API", "status": "passed", "start": 1715148587371, "stop": 1715148587856}, {"name": "Перетаскиваем ингредиента в область сбора заказа", "status": "passed", "steps": [{"name": "Определяем локатор случайного ингредитента/его элемента", "status": "passed", "parameters": [{"name": "random_ingredient_id", "value": "'61c0c5a71d1f82001bdaaa6d'"}, {"name": "element_locator", "value": "['xpath', '//a[@href = \"/ingredient/{ingredient_id}\"]']"}], "start": 1715148587856, "stop": 1715148587856}], "parameters": [{"name": "random_ingredient_id", "value": "'61c0c5a71d1f82001bdaaa6d'"}], "start": 1715148587856, "stop": 1715148588463}, {"name": "Перетаскиваем ингредиента в область сбора заказа", "status": "passed", "steps": [{"name": "Определяем локатор случайного ингредитента/его элемента", "status": "passed", "parameters": [{"name": "random_ingredient_id", "value": "'61c0c5a71d1f82001bdaaa73'"}, {"name": "element_locator", "value": "['xpath', '//a[@href = \"/ingredient/{ingredient_id}\"]']"}], "start": 1715148588463, "stop": 1715148588464}], "parameters": [{"name": "random_ingredient_id", "value": "'61c0c5a71d1f82001bdaaa73'"}], "start": 1715148588463, "stop": 1715148589056}, {"name": "Кликаем по кнопке \"Оформить заказ\"", "status": "passed", "start": 1715148589056, "stop": 1715148589304}, {"name": "Проверяем отображение успешного модального окна с номером заказа", "status": "broken", "statusDetails": {"message": "TypeError: not all arguments converted during string formatting\n", "trace": "  File \"C:\\Users\\pev_stasis\\PycharmProjects\\Diplom\\Diplom3_ui_python\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\pev_stasis\\PycharmProjects\\Diplom\\Diplom3_ui_python\\pages\\constructor_page.py\", line 64, in check_open_success_screen_with_order_number\n    if self.wait_until_text_changes(ConstructorPageLocators.ORDER_NUMBER_ON_SUCCESS_SCREEN, '9999'):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pev_stasis\\PycharmProjects\\Diplom\\Diplom3_ui_python\\pages\\base_page.py\", line 42, in wait_until_text_changes\n    self.logger.error('Проблема:', e)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1568, in error\n    self._log(ERROR, msg, args, **kwargs)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1684, in _log\n    self.handle(record)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1700, in handle\n    self.callHandlers(record)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1762, in callHandlers\n    hdlr.handle(record)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1028, in handle\n    self.emit(record)\n  File \"C:\\Users\\pev_stasis\\PycharmProjects\\Diplom\\Diplom3_ui_python\\venv\\Lib\\site-packages\\_pytest\\logging.py\", line 387, in emit\n    super().emit(record)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1168, in emit\n    self.handleError(record)\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 1160, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 999, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pev_stasis\\PycharmProjects\\Diplom\\Diplom3_ui_python\\venv\\Lib\\site-packages\\_pytest\\logging.py\", line 140, in format\n    return super().format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 703, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pev_stasis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\logging\\__init__.py\", line 392, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~\n"}, "start": 1715148589304, "stop": 1715148594428}], "parameters": [{"name": "driver", "value": "<class 'selenium.webdriver.firefox.webdriver.WebDriver'>"}], "start": 1715148587207, "stop": 1715148594434, "uuid": "589a7838-a821-44fb-ae89-6136a8aad6a5", "historyId": "33f23e9dca46244c1137aa61e564ecfb", "testCaseId": "92a82122663de568270b3dd429796da8", "fullName": "tests.test_constructor_page.TestConstructorPage#test_order_creation_by_authorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_constructor_page"}, {"name": "subSuite", "value": "TestConstructorPage"}, {"name": "host", "value": "DESKTOP-L83GKGS"}, {"name": "thread", "value": "18336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_constructor_page"}]}